#!/usr/local/bin/node

let fs = require("fs");
let Phrase = require("juandpineiro-palindrome");

let text = fs.readFileSync("phrases.txt", "utf-8");
text.split("\n").forEach(function(line) {
  let phrase = new Phrase(line);
  if (phrase.palindrome()) {
    fs.appendFileSync("palindromes.txt", `${line}\n`)
    console.log("palindrome detected:", line);
  }
});